### ISSUE TITLE
Deliverable

### ISSUE THREAD

**Issue by Ekwav** [Coflnet/SkyblockMod#1]
# Commands
Commands have 
* `type`(string) and 
* `data`(json string when receiving, base64 encoded json string when sending to the server)
## writeToChat
Should write the text in the chat and have a click action.
A click action starting with `/` should execute the command.
If the command starts with `/viewauction` the cursor should be moved up (see below for details).
A click action starting with `http` should open the link.
Every other action should be written to the chat input as is.
```
{"type":"writeToChat","data":"{\"text\":\"§3 xy click me\",\"onClick\":\"/ah uuid\"}"} 
```
## execute
the `execute` command should be executed directly with the same behavior as the `onClick` of `writeChat`
```
{"type":"execute","data":"/ah"}
```
## tokenLogin (serverCommand)
The login is handled via a token. The token should be sent by the client before any other command. It should be persisted in session storage and resent when the websocket is closed and reopened.
```
{"type":"tokenLogin","data":"base64(pasted token)"}
``` 
## clicked
The clicked command should be sent if the user clicks on a message received from `writeToChat`
```
{"type":"clicked","data":"base64(/ah uuid)"}
``` 

### How the cursor should be moved
The cursor should be moved up from the barrier to the gold nugget (the buy button)
![image](https://user-images.githubusercontent.com/16632490/130126142-9db71168-933f-488e-b343-5168ff4d8366.png)

**Comment by ToruiDev** [comment]
Execute and tokenLogin should be trivial.
What is "topic" in the command exactly?

**Comment by Ekwav** [comment]
I am sorry, looks like my phone auto-completion renamed `type` to `topic`.
I updated this

**Comment by Ekwav** [comment]
@ToruiDev v1 of the websocket is available via `wss://sky-commands.coflnet.com/modsocket?uuid={minecraftUuid}`

**Comment by ToruiDev** [comment]
Still missing:
- [ ] Player UUID
- [ ] First trying WSS then fallback to WS
- [ ] Cursor movement
~Conditional Server Activation~

**Comment by Ekwav** [comment]
Debug "command received" message will only get returned when the `SId` (session id) **starts with** `debug`
Thereby the parameter name for `session UUID` is set to `SId`
