### ISSUE TITLE
TFM Gui now working as expected anymore

### ISSUE THREAD

**Issue by matthias-luger** [Coflnet/SkyblockMod#112]
The TFM GUI doesn't work as expected anymore (mainly with bed flips).
The issue for this seems to be https://github.com/Coflnet/SkyblockMod/pull/103 as the middle click was changed to a left click action.

The left click picks up the item for a short moment, therefore the item doesn't exist in that slot anymore, causing the TFM GUI to not work correctly anymore.

Before wasting too much time debugging and rewriting parts of the TFM logic, what exactly was the reason we changed it @Ekwav?
According to this forum post https://hypixel.net/threads/update-regarding-modifications-sending-invalid-clicks.5130489/page-8#post-36853060 it is perfectly fine as long as it's implemented correctly (mode 3, not 0).

**Comment by Ekwav** [comment]
I don't know why you changed it, I just reviewed it and it seemed to work, didn't spam click.

**Comment by matthias-luger** [comment]
fixed by bef2ffc97f9f308beac5685c28fcf7283d2d4cfb
