### ISSUE TITLE
Extend DescriptionHandler to highlight item slots

### ISSUE THREAD

**Issue by Ekwav** [Coflnet/SkyblockMod#113]
It should be possible that items are highlighted based on a description modification.  
The to be added `HIGHLIGHT` Modification type should support different colors for highlighting, ideally RGB hex codes.  
Target supported modification JSON:
```json
{
      "type": "HIGHLIGHT",
      "line": 0, // can be ignored
      "value": "ff0000"
}
```
The highlight should stay present as long as the description is present for the item in that slot.   
There is a **150€ bounty** on implementing this (submitting a feature complete PR that gets merged)   
The mod size should not increase by more than 2kb and be compatible with NEU and skytils.  
Open for discussions.

**Comment by nea89o** [comment]
> The mod size should not increase by more than 2kb and be compatible with NEU and skytils.
2kb is pretty wack, tbh. A single class file is easily bigger than that even with just one method. In fact, it is impossible on most modern filesystems to make a file that is smaller than 4kb, since that is the smallest block size.

Also what does "compatible with NEU and skytils" mean? Also highlight in the NEU itemlist — that would be pretty much impossible with some major class transformations which would easily break on the next NEU version.

**Comment by Ekwav** [comment]
> > The mod size should not increase by more than 2kb and be compatible with NEU and skytils.
> 
> 2kb is pretty wack, tbh. A single class file is easily bigger than that even with just one method. In fact, it is impossible on most modern filesystems to make a file that is smaller than 4kb, since that is the smallest block size.
> 
> Also what does "compatible with NEU and skytils" mean? Also highlight in the NEU itemlist — that would be pretty much impossible with some major class transformations which would easily break on the next NEU version.

To my knowledge the 4kb block size doesn't matter because the file will be in the jar (wich is a single zip file) but sure lets bump it to 4kb for another block. Note that that the size meant is not storage size on disk, that file/download size which doesn't have block sizes.

It means that minecraft shouldn't crash because of a modification creating an error with those other mods. They should be usable side by side. The last added feature was an overlay which clashes with a NEU overlay so that is why its mentioned separately.

**Comment by Ekwav** [comment]
Thank you very much :blush:
