### ISSUE TITLE
Buy overlay breaks if auction in grace period

### ISSUE THREAD

**Issue by Ekwav** [Coflnet/SkyblockMod#115]
It should not break. Reported by @aron_643 with this video

https://github.com/Coflnet/SkyblockMod/assets/16632490/b584435b-6328-4857-992b-ce1fad313739

**Comment by matthias-luger** [comment]
Is he using the newest mod version? There is a check if the item is a bed...
On the otherhand, I think this check has always been there, so an older mod version should not be the reason.

I tested it myself and can't break it. I get this message:
![Image](https://github.com/Coflnet/SkyblockMod/assets/58751503/52dce47a-71d2-4a90-b942-44ddb66f84d0)
