### ISSUE TITLE
update server callbacks

### ISSUE THREAD

**Issue by Ekwav** [Coflnet/SkyblockMod#16]
Update the `clicked` callback command to use type `clicked` instead of the current `tokenLogin`
Add a callbacks when an item is bought. 
ie. The gold nuget is clicked, send `purchaseStart` 
The green_terracotta is clicked, send `purchaseConfrim`
both should contain the auction uuid and if possible the item `uuid` extracted from the NBT data.
Data format:
`{"auctionId":"abc123","itemId":"321abc"}`

**Comment by matthias-luger** [comment]
@Ekwav After you clicked the green terracotta you can't be sure that you got the item, right? Should @ToruiDev  somehow check if he got the item (inventory check, maybe?) or should the backend check if the player won the auction

**Comment by ToruiDev** [comment]
Where do i get the AuctionUUID from?
I can get the ItemUUID from the item but have no clue about the Auction.
Is the AuctionUUID the one from /viewauction <uuid>?
