### ISSUE TITLE
Detect out of budget flips

### ISSUE THREAD

**Issue by Ekwav** [Coflnet/SkyblockMod#31]
Flips now contain the `cost`, the scroeboard contains the available coins.
Flips that cost more than the available cost should be blocked or marked as to expensive.
There may be a setting to toggle hiding them.

**Comment by compsy0075** [comment]
just waste a few ms to fetch purse api and compare cost 🤦

**Comment by Ekwav** [comment]
> just waste a few ms to fetch purse api and compare cost 🤦 

There are too many users to do that on the server

**Comment by Ekwav** [comment]
Was merged as part of #58
