### ISSUE TITLE
Add /cofl status 

### ISSUE THREAD

**Issue by Ekwav** [Coflnet/SkyblockMod#4]
The `status` subcommand should print status information including but not limited to:
* Java version
* Server-connection status
* session age/info

**Comment by ToruiDev** [comment]
Please Review

**Comment by Ekwav** [comment]
session age/info is mission

**Comment by ToruiDev** [comment]
The last two parameters convey session info (isConnected, ConnectionState).

If any other information is required it would need to be kept (url, age) just for this status info.

**Comment by Ekwav** [comment]
> The last two parameters convey session info (isConnected, ConnectionState).
> 
> If any other information is required it would need to be kept (url, age) just for this status info.

The session contains `timestampCreated`. And that tells the session age

**Comment by Ekwav** [comment]
LGTM!
