### ISSUE TITLE
Receive a configuration after authentication

### ISSUE THREAD

**Issue by ToruiDev** [Coflnet/SkyblockMod#42]
after authentication the server should send some sort of confirutation object to allow the mod to opt into features.

@Ekwav can define the format.
this could be used to enable and disable other/future features in the mod using a web UI.

(e.g. ctrl+hover over item, etc.)

**Comment by Ekwav** [comment]
Mod settings should be a one  dimensional JSON object with the keys 
- chatRegex (matches will be sent)
- collectChat (at all)
- collectInventories
- collectTab 
- collectScoreboard
- allowProxy usage (proxies http requests with the users API key)
- collectInvClicks (items clicked in hypixels custom inventory UI)
- collectChatClicks 
- collectLobbyChanges 
- collectCoordinates 
- collectEntities 

Any changes from the server (on repeated calls) should be logged to the chat as "XY got activated", with a local setting to disable the message.

Collect Lobby Changes (world changes) could be very useful to detect joining/leaving of Skyblock in general or specific islands to deactivate/activate other collection categories from the server.

**Comment by Ekwav** [comment]
@ToruiDev as discussed this issue should have priority now

**Comment by Ekwav** [comment]
@ToruiDev a mock version of the settings get sent out with type `privacySettings` when connecting with `1.4-Alpha` as version string
