### ISSUE TITLE
Inventory Changesets

### ISSUE THREAD

**Issue by ToruiDev** [Coflnet/SkyblockMod#44]
On Chest open store the content of alll items.
On Chest close diff them.

if there is any change (e.g. transfer from chest to player, etc.) send the changes to the server.

this feature should be opt in only.

**Comment by Ekwav** [comment]
this can/will be done on the backend through uploading the whole inventory if #68 is fixed.  
It also allows the descriptions of specific items to contain summaries or warnings (in case of creating an undervalued auction)
