### ISSUE TITLE
Item descriptions need to be refreshed in some UIs

### ISSUE THREAD

**Issue by Ekwav** [Coflnet/SkyblockMod#68]
The gui isn't reopened in eg. trade views thus the descriptions for items the other trade side adds into the windows don't have any description.
The new description needs to be loaded for all items when a new item is added (intending to add a summary on the confirm button)

**Comment by Ekwav** [comment]
maybe check the content once a second and rerun if changed

**Comment by TGWaffles** [comment]
No please don't, use the packet instead

**Comment by Ekwav** [comment]
> No please don't, use the packet instead

@TGWaffles do you coincidentally know what package that is and/or can link me to documentation?
