### ISSUE TITLE
Add an playSound command 

### ISSUE THREAD

**Issue by Ekwav** [Coflnet/SkyblockMod#7]
The playSound Command should play a minecraft sound (identifier passed via `data`) inside the game.
This is an userrequested addition to get the attention to the last sent message that is deemed important.

**Comment by ToruiDev** [comment]
Is Implemented but needs further testing.
So far i was only able to get it to work passing in "random.explode" or "minecraft:random.explode".
This may only be, because i have no clue how the sounds in 1.8.9 are named.

Such a "Debug" Command is currently injected when you execute `/cofl debug`

**Comment by Ekwav** [comment]
The current implementation does not json-decode the passed `data` (the backend does a json-encode tho)
Should this command receive a plain string or do you add a json-decode to all commands?

**Comment by Ekwav** [comment]
LGTM!
