### ISSUE TITLE
Add custom bin view

### ISSUE THREAD

**Issue by Ekwav** [Coflnet/SkyblockMod#72]
There should be a custom bin auction view/overlay that only requires clicking the mouse twice instead of moving it to start and confirm the purchase.  
it should always display the item lore when opening and have a cancle button where it normally is (on the right)
The item lore is available as property on every flip message so should not have to be waited for to be loaded from hypixel. 
The interface should open as soon as the viewauction command is executed via a click on the message or the hotkey.
The flip message for the flip received from the server should optionally be displayed on the left side (changeable via in game setting)
The item icon should be rendered as soon as its available.

The bounty for implementing this is **200€ or 77,500 cofl coins (about 300€)**
Please keep in mind that there might be more minor adjustments until accepted.

Opening should look similar to this:

![Image](https://user-images.githubusercontent.com/16632490/194765713-b3abff80-6e7d-4ce2-9360-85947b44855d.png)

**Comment by Ekwav** [comment]
Note that I am just not capeable to make such an overlay but can hook it up to the events from the server so a class with public methods like `openFlipGui(IChatComponent message, string[] lore)` that then reacts/interacts with the hypixel events would do

**Comment by ForBai** [comment]
Hey Ekwav,
i don't know if anyone is already working on implementing this feature but i possibly could do that but.
I would need like 1 week for it if understood that correctly but i still would have some questions:

1. Should it have a special color?
2. Should it have rounded corners?

Thanks for reading

**Comment by Ekwav** [comment]
> Hey Ekwav,
> i don't know if anyone is already working on implementing this feature but i possibly could do that but.
> I would need like 1 week for it if understood that correctly but i still would have some questions:
> 
> 1. Should it have a special color?
> 2. Should it have rounded corners?
> 
> Thanks for reading

Hello @ForBai 
I don't know of anyone actively working on it. Most people I contacted said they don't have time to do it.  
To answer your questions
1. The ui doesn't have any special requirements except the ones listed. Would appreciate if it doesn't look ugly but I think I would be capable of adjusting the style myself if in doubt.
2. It probably would look better with a border radius of like 10px.

**Comment by ForBai** [comment]
Thanks for your answer, as soon as i am home from school tmr i will Start working on it.

**Comment by Peletic** [comment]
dont u dare claim the bounty instead of me whoever else is doing this im almost finished

**Comment by Ekwav** [comment]
> Thanks for your answer, as soon as i am home from school tmr i will Start working on it.
> I hope i get it done by end of the month. 

@paletic is working on implementing this now (as well) 
The bounty is paid to whoever made the PR that ends up getting merged into master

**Comment by ForBai** [comment]
Just got done, [pr](https://github.com/Coflnet/SkyblockMod/pull/74) is already created.
